package taika3d:ldb;

world storage-service {
    import wasi:clocks/wall-clock@0.3.0;
    import wasi:clocks/monotonic-clock@0.3.0;
    import wasi:sockets/types@0.3.0;
    import wasi:sockets/ip-name-lookup@0.3.0;
    import wasi:random/random@0.3.0;

    export wasi:cli/run@0.3.0;
}
