[build]
target = "wasm32-wasip3"

[target.wasm32-wasip3]
runner = [
    "wasmtime", "run",
    "-S", "p3=y",
    "-S", "inherit-network=y",
    "-W", "component-model=y",
    "-W", "component-model-async=y",
]

[unstable]
build-std = ["std", "panic_abort"]
